// scssを追加する場合はここに書いていく
import './scss/style.scss';

// TOPページ画像
import './images/about/about_title.png';
import './images/about/about_main.png';
import './images/about/about_card.png';
import './images/about/about_sauna.png';
import './images/about/about_onigiri.png';
import './images/about/about_goodmorning.png';
import './images/about/about_copy.png';
import './images/about/about_instagram.png';
// Profileページ画像
import './images/profile/profile_main.png';
// Worksページ画像
import './images/works/works_title.png';
import './images/works/works_detail1.jpg';
import './images/works/works_detail2.jpg';
import './images/works/works_detail3.jpg';
// Newsページ画像
import './images/news/news_title.png';
// Linksページ画像
import './images/links/links_title.png';
